In [2]:
import numpy as np 
import pandas as pd 

business_data = pd.read_json("data/yelp_academic_dataset_business.json", lines=True, orient='columns')
# user_data = pd.read_json("data/yelp_academic_dataset_user.json", lines=True, orient='columns', chunksize=200000)
review_data = pd.read_json("data/yelp_academic_dataset_review.json", lines=True, orient='columns', chunksize=200000)

In [3]:
business = business_data[business_data['is_open'] == 1]
business = business[['business_id','name','address', 'categories', 'attributes','stars']]
business

,business_id,name,address,categories,attributes,stars
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,"Shipping Centers, Local Services, Notaries, Ma...",{'BusinessAcceptsCreditCards': 'True'},3.0
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'RestaurantsDelivery': 'False', 'OutdoorSeati...",4.0
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,"Brewpubs, Breweries, Food","{'BusinessAcceptsCreditCards': 'True', 'Wheelc...",4.5
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'BusinessParking': 'None', 'BusinessAcceptsCr...",2.0
6,n_0UpQx1hsNbnPUSlodU8w,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point","Sporting Goods, Fashion, Shoe Stores, Shopping...","{'BusinessAcceptsCreditCards': 'True', 'Restau...",2.5
...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,"Nail Salons, Beauty & Spas","{'ByAppointmentOnly': 'False', 'RestaurantsPri...",3.0
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,"Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'BusinessAcceptsCreditCards': 'True', 'Restau...",4.0
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46","Shopping, Jewelry, Piercing, Toy Stores, Beaut...","{'RestaurantsPriceRange2': '1', 'BusinessAccep...",3.5
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,"Fitness/Exercise Equipment, Eyewear & Optician...","{'BusinessParking': '{'garage': False, 'street...",4.0
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'WheelchairAccessible': 'True', 'BusinessAcce...",4.5

In [4]:
# for u in user_data:
#     user = u[['user_id', 'name', 'average_stars']]
#     break

# user

In [5]:
for r in review_data:
    review = r[['review_id', 'user_id', 'business_id', 'stars']]
    break
        
review

,review_id,user_id,business_id,stars
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4
...,...,...,...,...
199995,nRYJWQ6YVjcrZCEU_JWrIQ,uakTslg3Ay3C0816-5yNdQ,idf-eiurCrbsLRcH7c9zmw,5
199996,4ylitTY7GmonnQDqhjB-eg,_fMw99otXOCu-Kzc-loMZA,v72HalBu5fQIFTD-oqhSgQ,5
199997,MnwNSr5h_t1uIlcj3aI_5w,ZfG1T_noQnbOdXnz4USs0Q,cvHY1RTAPSoH94ysP2_eyQ,5
199998,3fp0uXGAjIqgza02_ObF5w,I0MMq4iYjDjERnSjp76HDw,cBp1fn2LXpSHe4VbTXLYEw,5
199999,cSlJEcygfh-57otb6dF3Lg,sokS5Ml2QyKjOwO56pS9Jw,oBhJuukGRqPVvYBfTkhuZA,5

In [6]:
restaurant = business[business['categories'].str.contains('Restaurant.*')==True].reset_index()
restaurant

,index,business_id,name,address,categories,attributes,stars
0,3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'RestaurantsDelivery': 'False', 'OutdoorSeati...",4.0
1,5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'BusinessParking': 'None', 'BusinessAcceptsCr...",2.0
2,9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'RestaurantsAttire': ''casual'', 'Restaurants...",1.5
3,11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,"Vietnamese, Food, Restaurants, Food Trucks","{'Alcohol': ''none'', 'OutdoorSeating': 'None'...",4.0
4,12,il_Ro8jwPlHresjw9EGmBg,Denny's,8901 US 31 S,"American (Traditional), Restaurants, Diners, B...","{'RestaurantsReservations': 'False', 'Restaura...",2.5
...,...,...,...,...,...,...,...
34999,150323,w_4xUt-1AyY2ZwKtnjW0Xg,Bittercreek Alehouse,246 N 8th St,"Bars, Gastropubs, Sandwiches, Nightlife, Resta...","{'BikeParking': 'True', 'Alcohol': 'u'full_bar...",4.5
35000,150325,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,19 N Bishop Ave,"Restaurants, Sandwiches, Convenience Stores, C...","{'BikeParking': 'True', 'BusinessAcceptsCredit...",3.0
35001,150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,1181 N Milwaukee St,"Cafes, Juice Bars & Smoothies, Coffee & Tea, R...","{'WiFi': ''free'', 'RestaurantsGoodForGroups':...",4.0
35002,150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,"Restaurants, Mexican","{'WheelchairAccessible': 'False', 'Restaurants...",4.5
35003,150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,"Restaurants, Comfort Food, Food, Food Trucks, ...","{'RestaurantsDelivery': 'False', 'BusinessAcce...",4.5

In [7]:
# Function that extract keys from the nested dictionary
def extract_keys(attr, key):
    if attr == None:
        return "{}"
    if key in attr:
        return attr.pop(key)

# convert string to dictionary
import ast
def str_to_dict(attr):
    if attr != None:
        return ast.literal_eval(attr)
    else:
        return ast.literal_eval("{}")

In [8]:
# get dummies from nested attributes
restaurant['BusinessParking'] = restaurant.apply(lambda x: str_to_dict(extract_keys(x['attributes'], 'BusinessParking')), axis=1)
restaurant['Ambience'] = restaurant.apply(lambda x: str_to_dict(extract_keys(x['attributes'], 'Ambience')), axis=1)
restaurant['GoodForMeal'] = restaurant.apply(lambda x: str_to_dict(extract_keys(x['attributes'], 'GoodForMeal')), axis=1)
restaurant['Dietary'] = restaurant.apply(lambda x: str_to_dict(extract_keys(x['attributes'], 'Dietary')), axis=1)
restaurant['Music'] = restaurant.apply(lambda x: str_to_dict(extract_keys(x['attributes'], 'Music')), axis=1)

In [9]:
# create table with attribute dummies
df_attr = pd.concat([ restaurant['attributes'].apply(pd.Series), restaurant['BusinessParking'].apply(pd.Series),
                    restaurant['Ambience'].apply(pd.Series), restaurant['GoodForMeal'].apply(pd.Series), 
                    restaurant['Dietary'].apply(pd.Series) ], axis=1)
df_attr_dummies = pd.get_dummies(df_attr)
df_attr_dummies

,RestaurantsDelivery_False,RestaurantsDelivery_None,RestaurantsDelivery_True,OutdoorSeating_False,OutdoorSeating_None,OutdoorSeating_True,BusinessAcceptsCreditCards_False,BusinessAcceptsCreditCards_None,BusinessAcceptsCreditCards_True,BikeParking_False,...,latenight_False,latenight_True,lunch_False,lunch_True,dinner_False,dinner_True,brunch_False,brunch_True,breakfast_False,breakfast_True
0,1,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,1,0,1,0,1,0,1,0,1,0
4,0,0,1,1,0,0,0,0,1,1,...,1,0,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34999,0,1,0,0,1,0,0,0,1,0,...,0,1,0,1,0,1,1,0,1,0
35000,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
35001,1,0,0,0,0,1,0,0,1,0,...,1,0,1,0,1,0,1,0,1,0
35002,0,0,1,1,0,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,0
35003,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# get dummies from categories
df_categories_dummies = pd.Series(restaurant['categories']).str.get_dummies(',')
df_categories_dummies

,Acai Bowls,Accessories,Accountants,Active Life,Adult,Adult Entertainment,Advertising,Afghan,African,Air Duct Cleaning,...,Whiskey Bars,Wholesale Stores,Wholesalers,Wine Bars,Wine Tasting Room,Wine Tours,Wineries,Women's Clothing,Wraps,Yoga
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
result = restaurant[['business_id', 'name', 'stars']]

# Concat all tables and drop Restaurant column
df_final = pd.concat([result, df_attr_dummies, df_categories_dummies], axis=1)
df_final.drop('Restaurants',inplace=True,axis=1)

# map floating point stars to an integer
mapper = {1.0:1,1.5:2, 2.0:2, 2.5:3, 3.0:3, 3.5:4, 4.0:4, 4.5:5, 5.0:5}
df_final['stars'] = df_final['stars'].map(mapper)

df_final

,business_id,name,stars,RestaurantsDelivery_False,RestaurantsDelivery_None,RestaurantsDelivery_True,OutdoorSeating_False,OutdoorSeating_None,OutdoorSeating_True,BusinessAcceptsCreditCards_False,...,Whiskey Bars,Wholesale Stores,Wholesalers,Wine Bars,Wine Tasting Room,Wine Tours,Wineries,Women's Clothing,Wraps,Yoga
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,4,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,2,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,il_Ro8jwPlHresjw9EGmBg,Denny's,3,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34999,w_4xUt-1AyY2ZwKtnjW0Xg,Bittercreek Alehouse,5,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
35000,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,3,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35001,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,4,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
35002,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,5,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35003,2O2K6SXPWv56amqxCECd4w,The Plum Pit,5,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity

user_id_to_recommend = 'mh_-eMZ6K5RLWhZyISBhwA'
user_reviews_id = review[review['user_id'] == user_id_to_recommend]
highest_rated_reviews = user_reviews_id[user_reviews_id['stars'] == user_reviews_id['stars'].max()]

# Extract unique business_ids from user_reviews
business_ids = highest_rated_reviews['business_id']

business_ids

0        XQfwVwDr-v0ZS3_CbbE5Xw
45633    d_tRshM-w6S4QxE4VVi8tQ
Name: business_id, dtype: object

In [75]:
reviewed_rest_features = pd.merge(business_ids, df_final, on='business_id', how='inner')

# Find a feature with a value of 1 (except column 'business_id', 'name', 'stars')
features_with_ones = reviewed_rest_features.drop(['business_id', 'name', 'stars'], axis=1).any()

# Print and look at features of the user's preference
print("Features of the user's preference:")
for feature in features_with_ones[features_with_ones].index:
    if not feature.endswith('_False'):
        clean_feature_name = feature.split('_')[0]
        print(f"- {clean_feature_name}")

Features of the user's preference:
- RestaurantsDelivery
- OutdoorSeating
- BusinessAcceptsCreditCards
- RestaurantsPriceRange2
- RestaurantsTakeOut
- WiFi
- Alcohol
- RestaurantsAttire
- GoodForKids
- RestaurantsTableService
- RestaurantsGoodForGroups
- WheelchairAccessible
- NoiseLevel
- lot
- casual
- lunch
- brunch
- breakfast
-  American (New)
-  Breakfast & Brunch
-  Coffee & Tea
-  Food
-  Juice Bars & Smoothies
-  Sandwiches

In [15]:
# Create X (all the features) and y (target)
X = df_final.iloc[:,2:]
y = df_final['stars']

# Split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(X, y, test_size=0.2, random_state=1)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train_knn, y_train_knn)


accuracy_train = knn.score(X_train_knn, y_train_knn)
accuracy_test = knn.score(X_test_knn, y_test_knn)

print(f"Score on training set: {accuracy_train}")
print(f"Score on test set: {accuracy_test}")

Score on training set: 0.8226975681177017
Score on test set: 0.7997428938723039

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Assuming df_final and reviewed_rest_features have the same features
X_df_final = df_final.iloc[:, 2:]  # Assuming the features start from the third column
X_reviewed_rest_features = reviewed_rest_features.iloc[:, 2:]

# Calculate cosine similarity between all pairs of instances
cosine_sim = cosine_similarity(X_reviewed_rest_features, X_df_final)
cosine_sim_df = pd.DataFrame(cosine_sim.flatten(), columns=['similarity'])

# Concatenate the first two columns of df_final with result_df
concatenated_df = pd.concat([df_final.iloc[:, :2], cosine_sim_df], axis=1)

# Sort the DataFrame by 'similarity' column in descending order
concatenated_df.sort_values(by=["similarity"], inplace=True, ascending=False)

# Reset the index
concatenated_df.reset_index(inplace=True, drop=True)

              business_id                            name  similarity
0  XQfwVwDr-v0ZS3_CbbE5Xw    Turning Point of North Wales    1.000000
1  U9hqhH3gn7yGaSue3gQUUw             The Kettle & Grille    0.877733
2  MZssFQddj218X-68N5XwaA  The Turning Point of Blue Bell    0.870520
3  TZ9eAkKBKxj4HF_4rga9Gw       Turning Point - Bryn Mawr    0.863224
4  FYw5uf26ry8-MuPKD10z0Q    Josef's Vienna Bakery & Cafe    0.859605

In [26]:
recommend_rest = concatenated_df.head()
recommend_rest_info = pd.merge(restaurant, recommend_rest['business_id'], how='inner', on='business_id')

recommend_rest_info

,index,business_id,name,address,categories,attributes,stars,BusinessParking,Ambience,GoodForMeal,Dietary,Music
0,1867,XQfwVwDr-v0ZS3_CbbE5Xw,Turning Point of North Wales,1460 Bethlehem Pike,"Restaurants, Breakfast & Brunch, Food, Juice B...","{'NoiseLevel': 'u'average'', 'HasTV': 'False',...",3.0,"{'garage': False, 'street': False, 'validated'...","{'touristy': False, 'hipster': False, 'romanti...","{'dessert': False, 'latenight': False, 'lunch'...",{},{}
1,3764,FYw5uf26ry8-MuPKD10z0Q,Josef's Vienna Bakery & Cafe,933 W Moana Ln,"Grocery, Desserts, Breakfast & Brunch, Food, B...","{'WiFi': 'u'free'', 'RestaurantsReservations':...",4.0,"{'garage': False, 'street': False, 'validated'...","{'romantic': False, 'intimate': False, 'touris...","{'dessert': False, 'latenight': False, 'lunch'...",{},{}
2,32034,TZ9eAkKBKxj4HF_4rga9Gw,Turning Point - Bryn Mawr,925 W Lancaster Ave,"American (Traditional), Juice Bars & Smoothies...","{'BusinessAcceptsCreditCards': 'True', 'Outdoo...",3.5,"{'garage': False, 'street': False, 'validated'...","{'touristy': False, 'hipster': False, 'romanti...","{'dessert': False, 'latenight': False, 'lunch'...",{},{}
3,71378,MZssFQddj218X-68N5XwaA,The Turning Point of Blue Bell,994 Dekalb Pike,"Cafes, Restaurants, Breakfast & Brunch, Americ...","{'WiFi': ''free'', 'RestaurantsPriceRange2': '...",3.0,"{'garage': False, 'street': None, 'validated':...","{'touristy': False, 'hipster': False, 'romanti...","{'dessert': False, 'latenight': False, 'lunch'...",{},{}
4,145958,U9hqhH3gn7yGaSue3gQUUw,The Kettle & Grille,230 N Maple Ave,"Restaurants, American (New), Breakfast & Brunch","{'RestaurantsTableService': 'True', 'BikeParki...",4.0,"{'garage': False, 'street': False, 'validated'...","{'romantic': False, 'intimate': False, 'classy...","{'dessert': None, 'latenight': False, 'lunch':...",{},{}

In [48]:
recommend_rest_feature = pd.merge(df_final, recommend_rest['business_id'], how='inner', on='business_id')

recommend_rest_feature

,business_id,name,stars,RestaurantsDelivery_False,RestaurantsDelivery_None,RestaurantsDelivery_True,OutdoorSeating_False,OutdoorSeating_None,OutdoorSeating_True,BusinessAcceptsCreditCards_False,...,Whiskey Bars,Wholesale Stores,Wholesalers,Wine Bars,Wine Tasting Room,Wine Tours,Wineries,Women's Clothing,Wraps,Yoga
0,XQfwVwDr-v0ZS3_CbbE5Xw,Turning Point of North Wales,3,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,FYw5uf26ry8-MuPKD10z0Q,Josef's Vienna Bakery & Cafe,4,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,TZ9eAkKBKxj4HF_4rga9Gw,Turning Point - Bryn Mawr,4,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,MZssFQddj218X-68N5XwaA,The Turning Point of Blue Bell,3,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,U9hqhH3gn7yGaSue3gQUUw,The Kettle & Grille,4,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
import pandas as pd

# Calculate the sum of each column and obtain it as a Series.
column_sums = recommend_rest_feature.iloc[:, 3:].sum()

# Select only columns with a total of 1 or more. - There are 1342 features
filtered_columns = column_sums[column_sums >= 3]

# Delete the column when the name of the column ends with '_False'.
filtered_columns = filtered_columns[~filtered_columns.index.str.endswith('_False')]

print(filtered_columns)

RestaurantsDelivery_True           5
OutdoorSeating_True                4
BusinessAcceptsCreditCards_True    5
BikeParking_True                   3
RestaurantsPriceRange2_2           5
RestaurantsTakeOut_True            5
WiFi_'free'                        3
Alcohol_'none'                     4
RestaurantsAttire_'casual'         4
GoodForKids_True                   5
RestaurantsTableService_True       5
RestaurantsGoodForGroups_True      5
WheelchairAccessible_True          3
NoiseLevel_u'average'              4
lot_True                           5
casual_True                        4
lunch_True                         5
brunch_True                        4
breakfast_True                     5
 Breakfast & Brunch                5
 Coffee & Tea                      4
 Food                              4
 Juice Bars & Smoothies            3
 Restaurants                       3
 Sandwiches                        4
dtype: int64